### ISSUE TITLE
Building stella on Ubunutu 18.04

### ISSUE THREAD

**Issue by rahulgaur104** [mabarnes/stella#4]
Dear stella developers,

I can't compile stella on my linux system. I have set GK_SYSTEM = 'debian' and installed fftw3 and netcdf libraries ---I can run VMEC and GS2 without any problems. I have correctly set all the environment variables namely MAKEFLAGS, NETCDF_LIB_DIR, NETCDF_INC_DIR, FFT_LIB_DIR and FFT_INC_DIR. Upon running make I get the following error:

`
cpp -P -traditional -DFCOMPILER=_GFORTRAN_ -ffreestanding -DMPI -DNETCDF -DSPFUNC=_SPLOCAL_ utils/constants.fpp constants.f90`

`mpif90 -mkl -ffree-line-length-none -fno-backslash -fdefault-real-8 -fdefault-double-8  -O3 -I. -Iutils -Igeo/vmec_interface/mini_libstell -Igeo/vmec_interface -Igeo -I..     -I/usr/local/include    -c constants.f90
`

`
gfortran: error: unrecognized command line option ‘-mkl’
`

`
Makefile:287: recipe for target 'constants.o' failed
`
`
make: *** [constants.o] Error 1
rm constants.f90
`
Please help!

Thank you,
Rahul Gaur

**Comment by DenSto** [comment]
Try going into Makefile, and changing 

`F90FLAGS	= -mkl`

to 

`F90FLAGS	= -lapack`

If this doesn't work, try changing to
 
`F90FLAGS =`

**Comment by rahulgaur104** [comment]
Thanks for the help, Denis! I am assuming you meant

` F90FLAGS=-llapack`

 Upon trying both the suggested changes(F90FLAGS=-llapack and F90FLAGS= ) and running make I get a different error:

mpif90 -llapack -ffree-line-length-none -fno-backslash -fdefault-real-8 -fdefault-double-8  -O3 -I. -Iutils -Igeo/vmec_interface/mini_libstell -Igeo/vmec_interface -Igeo -I..     -I/usr/local/include    -c parallel_streaming.f90
cpp -P -traditional -DFCOMPILER=_GFORTRAN_ -ffreestanding -DMPI -DNETCDF -DSPFUNC=_SPLOCAL_ response_matrix.fpp response_matrix.f90
mpif90  -llapack -ffree-line-length-none -fno-backslash -fdefault-real-8 -fdefault-double-8  -O3 -I. -Iutils -Igeo/vmec_interface/mini_libstell -Igeo/vmec_interface -Igeo -I..     -I/usr/local/include    -c response_matrix.f90
cpp -P -traditional -DFCOMPILER=_GFORTRAN_ -ffreestanding -DMPI -DNETCDF -DSPFUNC=_SPLOCAL_ stella_io.fpp stella_io.f90
mpif90 -llapack -ffree-line-length-none -fno-backslash -fdefault-real-8 -fdefault-double-8  -O3 -I. -Iutils -Igeo/vmec_interface/mini_libstell -Igeo/vmec_interface -Igeo -I..     -I/usr/local/include    -c stella_io.f90
mpif90 -llapack -ffree-line-length-none -fno-backslash -fdefault-real-8 -fdefault-double-8  -O3 -I. -Iutils -Igeo/vmec_interface/mini_libstell -Igeo/vmec_interface -Igeo -I..     -I/usr/local/include    -c stella_diagnostics.f90
mpif90 -llapack -ffree-line-length-none -fno-backslash -fdefault-real-8 -fdefault-double-8  -O3 -I. -Iutils -Igeo/vmec_interface/mini_libstell -Igeo/vmec_interface -Igeo -I..     -I/usr/local/include    -c time_advance.f90
mpif90 -llapack -ffree-line-length-none -fno-backslash -fdefault-real-8 -fdefault-double-8  -O3 -I. -Iutils -Igeo/vmec_interface/mini_libstell -Igeo/vmec_interface -Igeo -I..     -I/usr/local/include    -c stella.f90
mpif90 -llapack -ffree-line-length-none -fno-backslash -fdefault-real-8 -fdefault-double-8  -O3 -I. -Iutils -Igeo/vmec_interface/mini_libstell -Igeo/vmec_interface -Igeo -I..     -I/usr/local/include    -o stella command_line.o common_types.o constants.o convert.o dissipation.o dist_fn.o dist_fn_arrays.o dist_redistribute.o euterpe_interface.o extended_zgrid.o fft_work.o fields.o fields_arrays.o file_utils.o finite_differences.o fzero.o g_tofrom_h.o gauss_quad.o gyro_averages.o init_g.o inputprofiles_interface.o job_manage.o kt_grids.o linear_solve.o millerlocal.o mirror_terms.o mp.o mt19937.o neoclassical_terms.o netcdf_utils.o parallel_streaming.o physics_flags.o physics_parameters.o ran.o redistribute.o response_matrix.o run_parameters.o sfincs_interface.o species.o spfunc.o spl.o stella.o stella_diagnostics.o stella_geometry.o stella_io.o stella_layouts.o stella_save.o stella_time.o stella_transforms.o text_options.o time_advance.o vmec_geo.o vmec_to_stella_geometry_interface.o vpamu_grids.o zgrid.o    -L/usr/local/lib -lnetcdff -lnetcdf     geo/vmec_interface/mini_libstell/mini_libstell.a
dissipation.o: In function `__dissipation_MOD_init_fp_conserve':
dissipation.f90:(.text+0xcf8a): undefined reference to `zgbtrs_'
dissipation.o: In function `__dissipation_MOD_advance_implicit_fp.constprop.6':
dissipation.f90:(.text+0x133fb): undefined reference to `zgbtrs_'
dissipation.f90:(.text+0x1447b): undefined reference to `zgbtrs_'
dissipation.o: In function `__dissipation_MOD_init_dissipation':
dissipation.f90:(.text+0x2d599): undefined reference to `zgbtrf_'
fft_work.o: In function `__fft_work_MOD_init_rcfftw':
fft_work.f90:(.text+0x149): undefined reference to `dfftw_plan_dft_r2c_1d_'
fft_work.o: In function `__fft_work_MOD_init_crfftw':
fft_work.f90:(.text+0x309): undefined reference to `dfftw_plan_dft_c2r_1d_'
fft_work.o: In function `__fft_work_MOD_init_ccfftw':
fft_work.f90:(.text+0x4e2): undefined reference to `dfftw_plan_dft_1d_'
fft_work.o: In function `__fft_work_MOD_delete_fft':
fft_work.f90:(.text+0x25): undefined reference to `dfftw_destroy_plan_'
stella_transforms.o: In function `__stella_transforms_MOD_finish_transforms':
stella_transforms.f90:(.text+0xc): undefined reference to `dfftw_destroy_plan_'
stella_transforms.f90:(.text+0x18): undefined reference to `dfftw_destroy_plan_'
stella_transforms.f90:(.text+0x24): undefined reference to `dfftw_destroy_plan_'
stella_transforms.f90:(.text+0x30): undefined reference to `dfftw_destroy_plan_'
stella_transforms.o:stella_transforms.f90:(.text+0x108): more undefined references to `dfftw_destroy_plan_' follow
stella_transforms.o: In function `__stella_transforms_MOD_transform_alpha2kalpha':
stella_transforms.f90:(.text+0x227): undefined reference to `dfftw_execute_dft_r2c_'
stella_transforms.o: In function `__stella_transforms_MOD_transform_kalpha2alpha':
stella_transforms.f90:(.text+0x615): undefined reference to `dfftw_execute_dft_c2r_'
stella_transforms.o: In function `__stella_transforms_MOD_transform_x2kx':
stella_transforms.f90:(.text+0x91f): undefined reference to `dfftw_execute_dft_r2c_'
stella_transforms.o: In function `__stella_transforms_MOD_transform_kx2x':
stella_transforms.f90:(.text+0xdc9): undefined reference to `dfftw_execute_dft_c2r_'
stella_transforms.o: In function `__stella_transforms_MOD_transform_y2ky_2d':
stella_transforms.f90:(.text+0x116c): undefined reference to `dfftw_execute_dft_'
stella_transforms.o: In function `__stella_transforms_MOD_transform_y2ky_5d':
stella_transforms.f90:(.text+0x1913): undefined reference to `dfftw_execute_dft_'
stella_transforms.o: In function `__stella_transforms_MOD_transform_ky2y_2d':
stella_transforms.f90:(.text+0x1f0f): undefined reference to `dfftw_execute_dft_'
stella_transforms.o: In function `__stella_transforms_MOD_transform_ky2y_5d':
stella_transforms.f90:(.text+0x25e7): undefined reference to `dfftw_execute_dft_'
collect2: error: ld returned 1 exit status
Makefile.target_stella:4: recipe for target 'stella' failed
make: *** [stella] Error 1
rm stella_io.f90 spfunc.f90 job_manage.f90 sfincs_interface.f90 stella_save.f90 command_line.f90 mp.f90 constants.f90 ran.f90 netcdf_utils.f90 response_matrix.f90 file_utils.f90

**Comment by alexvboe** [comment]
Hi Rahul,

Setting F90FLAGS=-llapack is correct. Could you try installing the ScaLAPACK and BLAS libaries before compiling, to make sure that you have a version of LAPACK available? 

Let me know how you get along. Best,

Alex

**Comment by rahulgaur104** [comment]
Hi Alex,

As per your suggestion, I changed F90FLAGS = -llapack, installed libscalapack-mpich-dev(dev for MPICH), libscalapack-mpich2.0(shared libs), libscalapack-openmpi-dev(dev for openmpi), libscalapack-openmpi2.0(shared libs) and reinstalled liblapack-dev(static version), liblapack3(shared version), libblas-dev(static), libblas3(shared)  using apt-get in Ubuntu. I did a make clean and ran make but I got the same error. 

Is there any other system I can try building stella on that would help the debugging process? Which system do you use?

Best,
Rahul

**Comment by alexvboe** [comment]
Hi Rahul,

The relevant line in your error message above is "undefined reference to zgbtrs_". Since zgbtrs is a LAPACK function, this suggests that no LAPACK library is found. I'm using stella on Marconi, where installing scaLAPACK and BLAS works. As a temporary workaround, you could replace your dissipation.f90 file (in which zgbtrs is called) with the dissipation.f90 file preceding the last commit on June 5th, 2020 (when the LAPACK dependence was introduced). 

Best,

Alex

**Comment by rahulgaur104** [comment]
Thanks for explaining the problem. I think I was able to build it successfully. I changed 
`F90FLAGS = -llapack`
to 
`F90FLAGS = -L/usr/lib/x86_64-linux-gnu/ -llapack`
and it ran without any errors! 

Is there a way to test if the build was successful?

**Comment by alexvboe** [comment]
Excellent - try running the code on a simple test case to check the build.
